language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-redirect --white-list linkedin.com,youtube.com --allow-dupe twitter.com,github.com,youtube.com,creativecommons.org
